# Package Overview
package_name: radio_fingerprint_model

# Data Files
training_data_file: rf_measurements_2k_dataset.csv

# Variables
# The variable we are attempting to predict (cnt)
target: cnt

pipeline_name: fingerprint_model
pipeline_save_file: fingerprint__model_output_v

# Features that will go inside processing pipeline
features:
  - servingCellID
  - ServingCellRSRP
  - Nbr1CellID
  - Nbr1RSRP
  - Nbr2CellID
  - Nbr2RSRP


unused_fields:  # Features to drop before pipeline



# Features names

servCellID_var: dteday
servCellRSRP_var: yr
nbr1CellID_var: mnth
nbr1RSRP_var: season
nbr2CellID_var: hr
nbr2RSRP_var: holiday

# Mappings for Ordinal categorical features

yr_mappings: 
  2011: 0
  2012: 1

# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Alogrithm parameters
n_estimators: 100
max_depth: 10
